spring:
  jpa:
    properties:
      show-sql: true
      format_sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: ${URL}
    username: ${USER}
    password: ${PASSWORD}

  properties:
    show-sql: true
    format_sql: true

  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

