spring:
  jpa:
    database: MYSQL

  datasource:
    url: { URL }
    username: { USERNAME }
    password: { PASSWORD }

  hibernate:
    ddl-auto: none

  properties:
    show-sql: true
    format_sql: true

  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS